Repository EFUB-SeeMe/SeeMe_Server, pull requests merged in 2021-07, with the labels that each got.

#30 fix bug, /covid/main
  src/main/java/com/seeme/service/CovidService.java
  src/main/java/com/seeme/service/api/MicrodustOpenApi.java
  src/main/java/com/seeme/util/CovidUtil.java
Labels: bug

#43 fix bug, /covid/regional, national
  src/main/java/com/seeme/service/api/CovidOpenApi.java
  src/main/java/com/seeme/util/CovidUtil.java
Labels: bug

#47 enhance location logic, add exception control, refactor
  src/main/java/com/seeme/controller/CovidController.java
  src/main/java/com/seeme/controller/LocationController.java
  src/main/java/com/seeme/controller/MicrodustController.java
  src/main/java/com/seeme/domain/location/Address.java
  src/main/java/com/seeme/domain/location/AddressCodeResDto.java
  src/main/java/com/seeme/domain/location/AddressResDto.java
  src/main/java/com/seeme/domain/location/UmdCodeResDto.java
  src/main/java/com/seeme/service/CovidService.java
  src/main/java/com/seeme/service/LocationService.java
  src/main/java/com/seeme/service/MicrodustService.java
  src/main/java/com/seeme/service/WeatherService.java
  src/main/java/com/seeme/service/api/CovidOpenApi.java
  src/main/java/com/seeme/service/api/LocationApi.java
  src/main/java/com/seeme/service/api/MicrodustOpenApi.java
  src/main/java/com/seeme/service/api/WeatherOpenApi.java
  src/main/java/com/seeme/util/LocationUtil.java
  src/main/java/com/seeme/util/WeatherUtil.java
Labels: bug, enhancement

#48 refactor weather main and week logic
  src/main/java/com/seeme/domain/weather/Weather.java
  src/main/java/com/seeme/service/WeatherService.java
  src/main/java/com/seeme/service/api/WeatherOpenApi.java
  src/main/java/com/seeme/util/WeatherUtil.java
Labels: enhancement

#53 /weather/week, fix week change error of getDayOfWeek
  src/main/java/com/seeme/util/WeatherUtil.java
Labels: bug
